# Form implementation generated from reading ui file 'qtui.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, form):
        form.setObjectName("Form")
        # Form.resize(804, 733)
        # form.resize(form.maximumSize().width(), form.maximumSize().height())
        form.resize(form.width() * 2, form.height() * 2)
        # form.resize(form.width(), form.height())

        self.groupBoxJson = QtWidgets.QGroupBox(form)
        # self.groupBox.setGeometry(QtCore.QRect(20, 10, 761, 471))
        self.groupBoxJson.setGeometry(form.rect())
        self.groupBoxJson.setObjectName("groupBoxJson")

        self.textEditTextJson = QtWidgets.QTextEdit(self.groupBoxJson)
        # self.textEdit.setGeometry(QtCore.QRect(20, 30, 351, 241))
        self.textEditTextJson.setGeometry(
            QtCore.QRect(20, 30, (self.groupBoxJson.width() / 2) - 40, self.groupBoxJson.height() / 2))
        # self.textEdit.setReadOnly(True)
        self.textEditTextJson.setObjectName("textEditTextJson")

        self.textEditResultJson = QtWidgets.QTextEdit(self.groupBoxJson)
        # self.textEditResultJson = QtWidgets.QPlainTextEdit(self.groupBoxJson)
        # self.plainTextEdit.setGeometry(QtCore.QRect(460, 40, 261, 161))
        self.textEditResultJson.setReadOnly(True)
        self.textEditResultJson.setGeometry(
            QtCore.QRect(self.textEditTextJson.geometry().right() + 41, 30, self.textEditTextJson.geometry().width(),
                         self.textEditTextJson.geometry().height()))
        self.textEditResultJson.setObjectName("textEditResultJson")

        self.pushButtonLoadJson = QtWidgets.QPushButton(self.groupBoxJson)
        self.pushButtonLoadJson.setGeometry(
            QtCore.QRect(20, self.textEditTextJson.geometry().bottom() + 20, self.textEditTextJson.geometry().width(),
                         50))
        self.pushButtonLoadJson.setObjectName("pushButtonLoadJson")

        self.pushButtonValidateJson = QtWidgets.QPushButton(self.groupBoxJson)
        self.pushButtonValidateJson.setGeometry(
            QtCore.QRect(self.textEditResultJson.geometry().left(), self.textEditTextJson.geometry().bottom() + 20,
                         self.textEditTextJson.geometry().width(), 50))
        self.pushButtonValidateJson.setObjectName("pushButtonValidateJson")

        self.groupBoxJsonParams = QtWidgets.QGroupBox(self.groupBoxJson)
        self.groupBoxJsonParams.setGeometry(QtCore.QRect(20, self.pushButtonValidateJson.geometry().bottom() + 10,
                                                         self.groupBoxJson.geometry().width() - 40, 400))
        self.groupBoxJson.setObjectName("groupBoxJsonParams")

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Валидатор xsd / json схем"))
        self.groupBoxJson.setTitle(_translate("Form", "Валидатор json"))
        self.pushButtonLoadJson.setText(_translate("Form", "Загрузить схему"))
        self.pushButtonValidateJson.setText(_translate("Form", "Валидировать схему"))
        self.groupBoxJsonParams.setTitle(_translate("Form", "Параметры валидации json"))
