# Form implementation generated from reading ui file 'qtui.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, form):
        form.setObjectName("Form")
        # form.resize(form.maximumSize().width(), form.maximumSize().height())
        form.resize(form.width() * 2, form.height() * 2)
        # form.resize(form.width(), form.height())

        self.tabWidget = QtWidgets.QTabWidget(form)

        self.jsonTab = QtWidgets.QWidget()
        self.xsdTab = QtWidgets.QWidget()
        self.tabWidget.addTab(self.jsonTab, "JSON")
        self.tabWidget.addTab(self.xsdTab, "XSD")

        self.tabWidget.setGeometry(form.rect())
        self.tabWidget.setObjectName("tabWidget")

        self.textEditTextJson = QtWidgets.QTextEdit(self.jsonTab)
        self.textEditTextJson.setGeometry(
            QtCore.QRect(20, 30, (self.tabWidget.width() / 2) - 40, self.tabWidget.height() / 2))
        self.textEditTextJson.setObjectName("textEditTextJson")

        self.textEditResultJson = QtWidgets.QListWidget(self.jsonTab)
        # self.textEditResultJson = QtWidgets.QTextEdit(self.tabWidget)
        # self.textEditResultJson.setReadOnly(True)
        self.textEditResultJson.setGeometry(
            QtCore.QRect(self.textEditTextJson.geometry().right() + 41, 30, self.textEditTextJson.geometry().width(),
                         self.textEditTextJson.geometry().height()))
        self.textEditResultJson.setObjectName("textEditResultJson")

        self.pushButtonLoadJson = QtWidgets.QPushButton(self.jsonTab)
        self.pushButtonLoadJson.setGeometry(
            QtCore.QRect(20, self.textEditTextJson.geometry().bottom() + 20, self.textEditTextJson.geometry().width(),
                         50))
        self.pushButtonLoadJson.setObjectName("pushButtonLoadJson")

        self.pushButtonValidateJson = QtWidgets.QPushButton(self.jsonTab)
        self.pushButtonValidateJson.setGeometry(
            QtCore.QRect(self.textEditResultJson.geometry().left(), self.textEditTextJson.geometry().bottom() + 20,
                         self.textEditTextJson.geometry().width(), 50))
        self.pushButtonValidateJson.setObjectName("pushButtonValidateJson")

        self.jsonParams = QtWidgets.QGroupBox(self.jsonTab)
        self.jsonParams.setGeometry(QtCore.QRect(20, self.pushButtonValidateJson.geometry().bottom() + 10,
                                                 self.tabWidget.geometry().width() - 40, 400))
        self.jsonParams.setObjectName("jsonParams")

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Валидатор xsd / json схем"))
        self.pushButtonLoadJson.setText(_translate("Form", "Загрузить схему"))
        self.pushButtonValidateJson.setText(_translate("Form", "Валидировать схему"))
        self.jsonParams.setTitle(_translate("Form", "Параметры валидации json"))
